# -*- coding: utf-8 -*-
"""UAS KDKA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GaAHpSjEYDIy-8C0N90AVwmk34E2dUzZ
"""

import numpy as np
import pandas as pd
import re
import string
from collections import Counter

df = pd.read_json("/content/EXIST2025_training.json", orient='index')

df.reset_index(inplace=True)

def preprocess_text(text):

    text = text.lower()
    text = re.sub(r'http\S+|www\S+', '', text)
    text = re.sub(r'@\w+', '', text)
    text = re.sub(r'#\w+', '', text)
    text = re.sub(r'\d+', '', text)
    text = text.translate(str.maketrans('', '', string.punctuation))

    words = text.split()

    stopwords = [
        'the', 'is', 'are', 'a', 'an',
        'and', 'or', 'to', 'of',
        'in', 'on', 'for', 'with',
        'this', 'that', 'it',
        'be', 'was', 'were',
        'at', 'by', 'from']

    stopwords += [
        'el', 'la', 'los', 'las',
        'de', 'que', 'y', 'en',
        'un', 'una', 'es',
        'por', 'para', 'con']

    filtered_words = []

    for word in words:
        if word not in stopwords:
            filtered_words.append(word)
    return filtered_words

X_text = df['tweet']
processed_text = X_text.apply(preprocess_text)

def majority_category(labels):
    flat_labels = []

    for sublist in labels:
        for item in sublist:
            if item != '-':
                flat_labels.append(item)
    if len(flat_labels) == 0:
        return "NON-SEXIST"
    return Counter(flat_labels).most_common(1)[0][0]

y = df['labels_task1_3'].apply(majority_category)

print("°❀⋆ DISTRIBUSI LABEL °❀⋆")
print(y.value_counts())

data = df[df['id_EXIST'] == 202685]

print("\n°❀⋆ PREPROCESSING SALAH SATU DATASET °❀⋆")
print("Sebelum: (｡•́︿•̀｡)")
print(data['tweet'].values[0])
print("\nSesudah: (｡•́︿•̀｡)")
print(preprocess_text(data['tweet'].values[0]))
print("\n°❀⋆ LABEL KLASIFIKASI °❀⋆")
print(majority_category(data['labels_task1_3'].values[0]))

from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

processed_text_joined = processed_text.apply(lambda tokens: ' '.join(tokens))

vectorizer = TfidfVectorizer(max_features=5000)
X = vectorizer.fit_transform(processed_text_joined)

df_tfidf = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())

print("°❀⋆.ೃ࿔*:･°❀⋆.ೃ࿔*:･HASIL TF-IDF°❀⋆.ೃ࿔*:･°❀⋆.ೃ࿔*:･")
print(f"Jumlah data   : {X.shape[0]}")
print(f"Jumlah fitur  : {X.shape[1]}")

print("\n°❀⋆ 20 FITUR PERTAMA °❀⋆")
print(vectorizer.get_feature_names_out()[:20])

sample_index = 4999
sample_tweet = processed_text_joined.iloc[sample_index]
sample_vector = X[sample_index]

tfidf_df = pd.DataFrame({
    'kata': vectorizer.get_feature_names_out(),
    'skor': sample_vector.toarray()[0]
})

df_tfidf.to_csv("hasil_tfidf.csv", index=False)

tfidf_df = tfidf_df[tfidf_df['skor'] > 0].sort_values('skor', ascending=False)

print(f"\n°❀⋆ TF-IDF TWEET KE-{sample_index} °❀⋆")
print(f"Tweet asli (｡•́︿•̀｡): {df['tweet'].iloc[sample_index]}")
print(f"Setelah preprocessing : {sample_tweet}")
print(f"\nKata-kata beserta skornya:")
print(tfidf_df.to_string(index=False))
print("Berhasil menyimpan TF-IDF ke hasil_tfidf.csv!")

import random
from collections import Counter

# ============ DATA PREP ============
X_manual = X.toarray().tolist()
y_manual = y.tolist()

# Buang UNKNOWN
mask = [i for i, label in enumerate(y_manual) if label != 'UNKNOWN']
X_manual = [X_manual[i] for i in mask]
y_manual = [y_manual[i] for i in mask]

# ============ FUNGSI-FUNGSI ============
def manual_train_test_split(X, y, test_size=0.2, seed=42):
    random.seed(seed)
    combined = list(zip(X, y))
    random.shuffle(combined)
    test_count = int(len(combined) * test_size)
    test_data = combined[:test_count]
    train_data = combined[test_count:]
    X_train, y_train = zip(*train_data)
    X_test, y_test = zip(*test_data)
    return list(X_train), list(X_test), list(y_train), list(y_test)

def calculate_gini(y_labels):
    if not y_labels:
        return 0
    counts = Counter(y_labels)
    total = len(y_labels)
    gini = 1.0
    for label in counts:
        p = counts[label] / total
        gini -= p ** 2
    return gini

def split_dataset(X, y, feature_index, threshold):
    left_X, left_y, right_X, right_y = [], [], [], []
    for i in range(len(X)):
        if X[i][feature_index] <= threshold:
            left_X.append(X[i])
            left_y.append(y[i])
        else:
            right_X.append(X[i])
            right_y.append(y[i])
    return left_X, left_y, right_X, right_y

def get_best_split(X, y, feature_indices):
    best_gini = 999
    best_criteria = None
    best_sets = None
    for feat_idx in feature_indices:
        thresholds = set(row[feat_idx] for row in X)
        for val in thresholds:
            l_X, l_y, r_X, r_y = split_dataset(X, y, feat_idx, val)
            if len(l_y) == 0 or len(r_y) == 0:
                continue
            p_left = len(l_y) / len(y)
            p_right = len(r_y) / len(y)
            gini_after = (p_left * calculate_gini(l_y)) + (p_right * calculate_gini(r_y))
            if gini_after < best_gini:
                best_gini = gini_after
                best_criteria = {'feature': feat_idx, 'threshold': val}
                best_sets = (l_X, l_y, r_X, r_y)
    return best_criteria, best_sets

def build_tree(X, y, max_depth=10, min_samples_split=5, depth=0, n_features=None):
    if (
        len(set(y)) == 1 or
        len(y) < min_samples_split or
        (max_depth is not None and depth >= max_depth)
    ):
        return {'leaf': True, 'label': Counter(y).most_common(1)[0][0]}

    total_features = len(X[0])
    if n_features is None:
        feature_indices = list(range(total_features))
    else:
        feature_indices = random.sample(range(total_features), min(n_features, total_features))

    best_criteria, best_sets = get_best_split(X, y, feature_indices)

    if best_criteria is None:
        return {'leaf': True, 'label': Counter(y).most_common(1)[0][0]}

    l_X, l_y, r_X, r_y = best_sets
    left_branch  = build_tree(l_X, l_y, max_depth, min_samples_split, depth + 1, n_features)
    right_branch = build_tree(r_X, r_y, max_depth, min_samples_split, depth + 1, n_features)

    return {
        'leaf'     : False,
        'feature'  : best_criteria['feature'],
        'threshold': best_criteria['threshold'],
        'left'     : left_branch,
        'right'    : right_branch,
    }

def predict_one(tree, x):
    if tree['leaf']:
        return tree['label']
    if x[tree['feature']] <= tree['threshold']:
        return predict_one(tree['left'], x)
    return predict_one(tree['right'], x)

def predict_tree(tree, X):
    return [predict_one(tree, x) for x in X]

def bootstrap_sample(X, y, seed=None):
    if seed is not None:
        random.seed(seed)
    n = len(X)
    indices = [random.randint(0, n - 1) for _ in range(n)]
    X_boot = [X[i] for i in indices]
    y_boot = [y[i] for i in indices]
    return X_boot, y_boot

def build_random_forest(X, y, n_estimators=30, max_depth=10,
                        min_samples_split=5, n_features=None, seed=42):
    trees = []
    total_features = len(X[0])
    if n_features is None:
        n_features = max(1, int(total_features ** 0.5))

    for i in range(n_estimators):
        X_boot, y_boot = bootstrap_sample(X, y, seed=seed + i)
        tree = build_tree(X_boot, y_boot, max_depth, min_samples_split, n_features=n_features)
        trees.append(tree)
        print(f"  Tree {i+1}/{n_estimators} selesai", end="\r")
    print()
    return trees

def predict_random_forest(trees, X):
    all_preds = [predict_tree(tree, X) for tree in trees]
    final_preds = []
    for i in range(len(X)):
        votes = [all_preds[t][i] for t in range(len(trees))]
        final_preds.append(Counter(votes).most_common(1)[0][0])
    return final_preds

def oversample(X, y, seed=42):
    random.seed(seed)
    counts = Counter(y)
    max_count = max(counts.values())
    X_out, y_out = list(X), list(y)
    for label, count in counts.items():
        if count < max_count:
            indices = [i for i, lbl in enumerate(y) if lbl == label]
            needed = max_count - count
            for _ in range(needed):
                idx = random.choice(indices)
                X_out.append(X[idx])
                y_out.append(y[idx])
    combined = list(zip(X_out, y_out))
    random.shuffle(combined)
    X_out, y_out = zip(*combined)
    return list(X_out), list(y_out)

def evaluate(y_true, y_pred, model_name="Model"):
    labels = sorted(set(y_true))
    correct = sum(1 for t, p in zip(y_true, y_pred) if t == p)
    accuracy = correct / len(y_true)

    recall_per_class = []
    for lbl in labels:
        tp = sum(1 for t, p in zip(y_true, y_pred) if t == lbl and p == lbl)
        fn = sum(1 for t, p in zip(y_true, y_pred) if t == lbl and p != lbl)
        recall = tp / (tp + fn) if (tp + fn) > 0 else 0
        recall_per_class.append(recall)
    balanced_acc = sum(recall_per_class) / len(recall_per_class)

    print(f"EVALUASI {model_name}")
    print(f"Accuracy          : {accuracy:.4f}")
    print(f"Balanced Accuracy : {balanced_acc:.4f}")
    print(f"\n{'Kelas':<35} {'Precision':>10} {'Recall':>10} {'F1':>10} {'Support':>10}")
    for lbl in labels:
        tp = sum(1 for t, p in zip(y_true, y_pred) if t == lbl and p == lbl)
        fp = sum(1 for t, p in zip(y_true, y_pred) if t != lbl and p == lbl)
        fn = sum(1 for t, p in zip(y_true, y_pred) if t == lbl and p != lbl)
        support = sum(1 for t in y_true if t == lbl)
        precision = tp / (tp + fp) if (tp + fp) > 0 else 0
        recall    = tp / (tp + fn) if (tp + fn) > 0 else 0
        f1        = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0
        print(f"{lbl:<35} {precision:>10.4f} {recall:>10.4f} {f1:>10.4f} {support:>10}")

    return accuracy, balanced_acc

# ============ EKSEKUSI ============
X_train, X_test, y_train, y_test = manual_train_test_split(X_manual, y_manual, test_size=0.2)
print(f"\n°❀⋆ SPLIT DATA °❀⋆")
print(f"Jumlah data training : {len(X_train)}")
print(f"Jumlah data testing  : {len(X_test)}")

X_train_bal, y_train_bal = oversample(X_train, y_train)
print(f"\nSetelah oversample: {Counter(y_train_bal)}")

print("\n°❀⋆ Training Decision Tree °❀⋆")
dt = build_tree(X_train_bal, y_train_bal, max_depth=10, min_samples_split=5)
print("Selesai!")

print("\n°❀⋆ Prediksi Decision Tree °❀⋆")
y_pred_dt = predict_tree(dt, X_test)
acc_dt, bal_acc_dt = evaluate(y_test, y_pred_dt, "Decision Tree")

print("\n°❀⋆ Training Random Forest °❀⋆")
rf_trees = build_random_forest(X_train_bal, y_train_bal, n_estimators=30,
                                max_depth=10, min_samples_split=5, n_features=200, seed=42)

print("\n°❀⋆ Prediksi Random Forest °❀⋆")
y_pred_rf = predict_random_forest(rf_trees, X_test)
acc_rf, bal_acc_rf = evaluate(y_test, y_pred_rf, "Random Forest")

print("\n°❀⋆ Perbandingan Decision Tree dan Random Forest °❀⋆")
print(f"{'Model':<20} {'Accuracy':>12} {'Balanced Acc':>15}")
print(f"{'Decision Tree':<20} {acc_dt:>12.4f} {bal_acc_dt:>15.4f}")
print(f"{'Random Forest':<20} {acc_rf:>12.4f} {bal_acc_rf:>15.4f}")
winner_acc     = "Random Forest" if acc_rf > acc_dt else "Decision Tree"
winner_bal_acc = "Random Forest" if bal_acc_rf > bal_acc_dt else "Decision Tree"
print(f"\nModel terbaik (Accuracy)          : {winner_acc}")
print(f"Model terbaik (Balanced Accuracy) : {winner_bal_acc}")